Repository standfirm/esa_feeder, pull requests merged in 2019-05, with the labels that each got.

#52 fix circleci no build step error
  .circleci/config.yml
Labels: REVIEW

#50 Set "required: false" for $SLACK_WEBHOOK_URL
  app.json
Labels: LGTM:2+

#49 Search also "Templates" category
  lib/esa_feeder/entities/esa_post.rb
  lib/esa_feeder/gateways/esa_client.rb
  spec/gateways/esa_client_spec.rb
Labels: LGTM:2+

#51 Improve exception messages
  lib/esa_feeder/gateways/esa_client.rb
Labels: LGTM:2+

#53 Migrate Ruby & Gem versions
  .circleci/config.yml
  .ruby-version
  Gemfile.lock
Labels: LGTM:1, REVIEW
